### ISSUE TITLE
Unable to parse input breakpoints ERROR

### ISSUE THREAD

**Issue by brucemoran** [PapenfussLab/clove#2]
Hi,

I am trying to use breakpoints from GRIDSS. I have tried VCF and BEDPE but get same error. I have made toy BEDPE, removed header, renamed columns as per [standard BEDPE](http://bedtools.readthedocs.io/en/latest/content/general-usage.html#bedpe-format) and it also generates the same error. Can you specify an exact file format that will be accepted, and all further input formats acceptable? 

Thanks,

Bruce.

**Comment by jibsch** [comment]
Hi Bruce,
We've included a GRIDSS-specific parser now in CLOVE. Please have a look at the latest release and let me know if it works for you.
Regards,
Jan
