### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException: For input string: "QUAL"

### ISSUE THREAD

**Issue by datakid** [PapenfussLab/clove#3]
We are seeing the following error, using clove 0.16 on CentOS 7.3 with Java 1.8.0_144

clove -i FR07937945--FR07937944_gridss.vcf.gridss_RPostProcess.bedpe BEDPE 
-b FR07937945_merged.bam 
-c 191 10 
-o clove_output.vcf
Reading input...
Exception in thread "main" java.lang.NumberFormatException: For input string: "QUAL"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at au.edu.wehi.clove.Event.createNewEventFromBEDPE(Event.java:387)
        at au.edu.wehi.clove.Clove.main(Clove.java:630)

I have done 

cut -f FR07937945--FR07937944_gridss.vcf.gridss_RPostProcess.bedpe

and confirmed that all of the second column (QUAL) are digits. Some are integers, but most are floats. 

Since line 387 of Event.java is

	int p1 = Integer.parseInt(bits[1]);

( https://github.com/PapenfussLab/clove/blob/c530dee9c91caf8ed96c3257682d6ef15b55f3ae/src/main/java/au/edu/wehi/clove/Event.java#L387 )

I guess there is an issue here. 

Is it that BEDPE files *shouldn't* have floats in the QUAL col, or is it that our file isn't a bedpe file, or is it that this is an error in clove?

head -n 1 on our bedpe file gives:

fusion  QUAL    svLen   seqnames        start   end     strand  SYMBOL  seqnames.B      start.B end.B   strand.B        SYMBOL.B      AS      ASCRP   ASCSR   ASQ     ASRP    ASSR    BA      BAQ     BEID    BQ      BSC     BSCQ    BUM     BUMQ    CQ   END      EVENT   HOMLEN  HOMSEQ  IHOMPOS IMPRECISE       MATEID  PARID   RAS     RASQ    REF     REFPAIR RP      RPQ     RSR  RSRQ     SC      SELF    SOMATIC SR      SRQ     SVLEN   SVTYPE  TEST    ASCRP.1 ASCRP.2 ASCSR.1 ASCSR.2 ASRP.1  ASRP.2  ASSR.1ASSR.2  BEID.1  BEID.2  BEID.3  BEID.4  BEID.5  BEID.6  BEID.7  BEID.8  BEID.9  BEID.10 BEID.11 BEID.12 BSC.1   BSC.2   BSCQ.1BSCQ.2  BUM.1   BUM.2   BUMQ.1  BUMQ.2  CIEND   CIEND.1 CIPOS   CIPOS.1 CIRPOS  CIRPOS.1        HOMLEN.1        HOMSEQ.1     IHOMPOS.1        IHOMPOS.2       REF.1   REF.2   REFPAIR.1       REFPAIR.2       RP.1    RP.2    RPQ.1   RPQ.2   RSR.1   RSR.2RSRQ.1   RSRQ.2  SR.1    SR.2    SRQ.1   SRQ.2   ID      QUAL.1  QUAL.2

**Comment by jibsch** [comment]
Hi,
It looks like a mismatch in format to me. 
The first six columns should describe the positions in Bedpe, not the quality. 
The quoted line is expecting to parse the first position (p1), not a quality value.
Have a look at the Bedpe-spec here: [http://bedtools.readthedocs.io/en/latest/content/general-usage.html](http://bedtools.readthedocs.io/en/latest/content/general-usage.html)
I hope this helps.

**Comment by datakid** [comment]
Apparently the data came out of GRIDSS that was run per howto in GRIDDS. Regardless, I think someone wrote a script to fix it.
