### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by acaprez** [PapenfussLab/clove#6]
Hello,

I was wondering what license Clove is released under.  I contribute to the [Bioconda project](https://bioconda.github.io), and am interested in adding Clove so it can easily be installed using the conda package manager.  All contributed packages are required to have a license that allows redistribution however.  If you are amenable to this, could you please update the license type to one that allows redistribution?  Thanks.

**Comment by jibsch** [comment]
Hi Adam,

I’ve added a license to the project.

Regards,

jan

**Comment by acaprez** [comment]
Hi Jan,

Great, thanks!  
FYI, Clove is now available in Bioconda:  https://bioconda.github.io/recipes/clove/README.html
