### ISSUE TITLE
Bam file input

### ISSUE THREAD

**Issue by saty89** [PapenfussLab/clove#9]
Hi, When using GRIDSS input do we need to use the actual bam file or the <assembly>.bam that GRIDSS generates ?

**Comment by d-cameron** [comment]
The actual bam file. The GRIDSS assembly bam only contains the contigs thus is an inappropriate source for (e.g.) determining coverage.

**Comment by dr-ashu-geno** [comment]
Dear Daniel

Does Clove support CRAM file too??

Thanks in advance,
Best
